authentication:
  username: admin
  password: password

# foreground_processing: true

# token_length: 8

# temp_links:
#   invalidate_after: 86400

# file_release_token: ooH3yathu9Eey2vi

label_image:
  bin: lib/label_image/label_image
  graph: lib/label_image/inception_v3_2016_08_28_frozen.pb
  labels: lib/label_image/imagenet_slim_labels.txt
